# Generated by Django 3.1.1 on 2021-01-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='', upload_to='photos'),
            preserve_default=False,
        ),
    ]
